kind: pipeline
type: docker
name: freeday-web

trigger:
  branch:
  - dev
  event:
  - push
  - pull_request

services:
- name: mongo
  image: mongo:latest
- name: freeday-api
  image: freedayapp/freeday
  environment:
    ENVIRONMENT: test
    PUBLIC_URL: http://localhost:8788/
    PORT: 8787
    TEST_USERNAME: testuser
    TEST_PASSWORD: testpassword
    MONGO_URL: mongodb://mongo:27017/freeday-test
    MONGO_TEST_URL: mongodb://mongo:27017/freeday-test
    SLACK_ENABLED: false
    SLACK_CLIENT_ID: 1234
    DIALOGFLOW_ENABLED: false

steps:
- name: install
  image: node:14
  pull: if-not-exists
  commands:
  - npm ci
- name: lint
  image: node:14
  pull: if-not-exists
  commands:
  - npm run lint
  depends_on:
  - install
- name: test
  image: mcr.microsoft.com/playwright:v1.23.3-focal
  pull: if-not-exists
  commands:
  - cp .env.ci .env
  - npm run test
  depends_on:
  - install
- name: sonarqube
  image: pitininja/drone-sonar-plugin:latest
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  depends_on:
  - install
  when:
    branch:
    - dev
    event:
    - push

---
kind: pipeline
type: docker
name: freeday-docker

trigger:
  event:
  - tag

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/freeday-app/freeday-docker.git .
- name: docker  
  image: plugins/docker
  settings:
    repo: freedayapp/freeday
    tags:
    - ${DRONE_TAG}
    - latest
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
